#!/usr/bin/env python3
"""
CV Tailor - generates a role-targeted LaTeX CV from the master CV
(cv/master_ismail.tex) with ZERO fabricated facts.

Honest tailoring only:
  1. Reorder experience bullets inside each cventry by JD-keyword overlap.
  2. Keep bullet text verbatim from the master (no invention).
  3. Track targeted JD keywords in file header comments.

Usage:
  python3 tools/tailor_cv.py --jd jd.txt --company Acme --role "Backend Engineer"
  python3 tools/tailor_cv.py --verify cv/main_acme_backend_engineer.tex
"""

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MASTER = REPO_ROOT / "cv" / "master_ismail.tex"

# Same keyword bank as ats_scorer.py — keep both in sync.
TECH_KEYWORDS = {
    "typescript": [r"typescript"],
    "javascript": [r"javascript"],
    "go":         [r"\bgolang\b", r"\bgo\b(?=\s*(?:micro|dev|developer|programming|services|backend))"],
    "java":       [r"\bjava\b", r"spring\s*boot"],
    "dart":       [r"\bdart\b"],
    "swift":      [r"\bswift\b"],
    "next.js":    [r"next\.?js"],
    "react":      [r"\breact\.?js\b", r"\breact\b"],
    "react native": [r"react\s*native"],
    "flutter":    [r"\bflutter\b"],
    "express.js": [r"express\.?js", r"\bexpress\b"],
    "spring boot": [r"spring\s*boot"],
    "postgresql": [r"postgres(?:ql)?"],
    "mysql":      [r"\bmy\s?sql\b"],
    "mongodb":    [r"mongo(?:db)?"],
    "oauth":      [r"\boauth\b"],
    "rest":       [r"\brest(?:ful)?\b"],
    "ci/cd":      [r"\bci/?cd\b", r"pipelines?"],
    "git":        [r"\bgit\b"],
    "docker":     [r"\bdocker\b"],
    "ios":        [r"\bios\b"],
    "android":    [r"\bandroid\b"],
    "agile/scrum": [r"\bscrum\b", r"\bagile\b"],
    "performance": [r"performance|optimi[sz]ation|scalab"],
    "security":   [r"security"],
    "testing":    [r"testing|unit tests?"],
    "documentation": [r"document"],
    "collaboration": [r"collaborat"],
}


def find_jd_keywords(jd_text: str) -> list:
    found = []
    for kw, patterns in TECH_KEYWORDS.items():
        if any(re.search(p, jd_text, re.IGNORECASE) for p in patterns):
            found.append(kw)
    return found


def bullet_score(bullet: str, jd_kws: list) -> int:
    """How many JD keywords does this bullet text hit?"""
    low = bullet.lower()
    return sum(1 for kw in jd_kws
               if any(re.search(p, low) for p in TECH_KEYWORDS.get(kw, [])))


CVENTRY_RE = re.compile(
    r"\\item\{\\cventry\{[^}]*\}\{[^}]*\}.*?\\end\{itemize\}\}\}",
    re.DOTALL,
)
INNER_BULLET_RE = re.compile(r"^\s*\\item (?!\{\\cventry)(.*)$", re.MULTILINE)


def reorder_cventry_block(block: str, jd_kws: list) -> str:
    """Sort the inner \item lines inside one cventry block by score (stable)."""
    m = re.search(r"\\begin\{itemize\}(.*?)\\end\{itemize\}", block, re.DOTALL)
    if not m:
        return block
    body = m.group(1)
    if "\\item" not in body:
        return block
    bullet_bodies = re.findall(
        r"\\item (.+?)(?=(?:\n\s*\\item)|\Z)",
        body.strip(),
        re.DOTALL,
    )
    scored = sorted(bullet_bodies, key=lambda b: -bullet_score(b, jd_kws))
    new_body = "\n" + "\n".join("    \\item " + b.strip() for b in scored) + "\n"
    return block[:m.start(1)] + new_body + block[m.end(1):]


def tailor(master: str, jd_kws: list, company: str, role: str) -> str:
    out = master
    out = out.replace(
        "%% Master CV - Ismail Nur Alam\n",
        f"%% Tailored CV - Ismail Nur Alam | {role} @ {company}\n"
        f"%% Generated by tools/tailor_cv.py from cv/master_ismail.tex\n"
        f"%% JD keywords targeted: {', '.join(jd_kws) or '-'}\n",
    )
    out = out.replace("pdftitle={Ismail Nur Alam - CV}",
                      "pdftitle={Ismail Nur Alam - %s}" % role)
    out = out.replace("%% Compile with: lualatex master_ismail.tex\n",
                      "%% Compile with: lualatex main_<company>_<role>.tex\n")

    # Reorder bullets inside each cventry block.
    blocks = CVENTRY_RE.findall(out)
    for block in blocks:
        out = out.replace(block, reorder_cventry_block(block, jd_kws))
    return out


def verify(tailored_path: Path) -> int:
    """Audit: every experience bullet in the tailored CV must exist verbatim
    in the master CV (zero-fabrication gate)."""
    master = MASTER.read_text(encoding="utf-8")
    tailored = tailored_path.read_text(encoding="utf-8")

    def extract_bullets(text: str) -> list:
        return [b.strip() for b in INNER_BULLET_RE.findall(text)]

    master_items = set(extract_items(master))
    tailored_items = extract_items(tailored)
    fabricated = [b for b in tailored_items if b not in master_items]
    print(f"Tailored bullets: {len(tailored_items)}")
    print(f"Master bullets:   {len(master_items)}")
    if fabricated:
        print("FABRICATED BULLETS FOUND:")
        for b in fabricated:
            print("  >>", b[:120])
        return 1
    print("PASS: all bullets verbatim from master.")
    return 0


def extract_items(text: str) -> list:
    """Extract bullet text lines (excluding cventry headers)."""
    items = []
    for m in re.finditer(r"\n\s*\\item\s+(.+?)(?=\n\s*\\item|\Z)", text, re.DOTALL):
        chunk = m.group(1).strip()
        if chunk.startswith("{\\cventry"):
            continue
        chunk = re.sub(r"\\end\{itemize\}.*$", "", chunk, flags=re.DOTALL).strip()
        chunk = re.sub(r"\\end\{document\}.*$", "", chunk, flags=re.DOTALL).strip()
        chunk = chunk.rstrip("}").strip()
        if chunk:
            items.append(chunk)
    return items


def slug(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", s.lower()).strip("_")


def main():
    ap = argparse.ArgumentParser(description="Grounded CV tailoring engine")
    ap.add_argument("--jd", help="JD text file path (generation mode)")
    ap.add_argument("--company", help="Company name (generation mode)")
    ap.add_argument("--role", help="Role title (generation mode)")
    ap.add_argument("--verify", help="Verify a produced .tex (audit mode)")
    ap.add_argument("--out", help="Output .tex path (default cv/main_<company>_<role>.tex)")
    args = ap.parse_args()

    if args.verify:
        sys.exit(verify(Path(args.verify)))

    if not (args.jd and args.company and args.role):
        ap.error("Provide --jd/--company/--role for generation, or --verify for audit")

    jd_text = Path(args.jd).read_text(encoding="utf-8")
    master = MASTER.read_text(encoding="utf-8")
    jd_kws = find_jd_keywords(jd_text)

    out_path = Path(args.out) if args.out else \
        REPO_ROOT / "cv" / f"main_{slug(args.company)}_{slug(args.role)}.tex"
    out = tailor(master, jd_kws, args.company, args.role)
    out_path.write_text(out, encoding="utf-8")
    print(f"Wrote {out_path}")
    print(f"JD keywords targeted: {jd_kws or '-'}")
    # Run grounding audit immediately
    sys.exit(verify(out_path))


if __name__ == "__main__":
    main()
